
package itson.proyectofinal.presentacion;

import itson.proyectofinal.Grafo;
import itson.proyectofinal.grafo.MapaCiudades;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MapaEstado extends javax.swing.JFrame {
    
    private CardLayout cardLayout;

    public MapaEstado() {
        initComponents();
        mostrarMapa();
        setLocationRelativeTo(null);
        
        cardLayout = new CardLayout();
        jPanelPaneles.setLayout(cardLayout);
        JPanel panelVacio = new JPanel(); 
        jPanelPaneles.add(panelVacio, "vacio");
        panelVacio.setOpaque(false);
        jPanelPaneles.add(new PanelMST(this), "MST");
        jPanelPaneles.add(new PanelRutaCorta(this), "RutaCorta");
        jPanelPaneles.add(new PanelRecorridos(this), "Recorridos");
        
        mostrarPanel("vacio");

    }
    
    public void mostrarPanel(String nombrePanel) {
        CardLayout cl = (CardLayout) jPanelPaneles.getLayout();
        cl.show(jPanelPaneles, nombrePanel);
    }


    private void mostrarMapa() {
        Grafo grafoCiudades = MapaCiudades.construirGrafo();

        MapaPanel mapaPanel = new MapaPanel(grafoCiudades);

        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(mapaPanel, BorderLayout.CENTER);

        mapaPanel.setSize(jPanel1.getSize());
    }
    
    private void ocultarBotones() {
        jButtonMST.setVisible(false);
        jButtonRecorrido.setVisible(false);
        jButtonSP.setVisible(false);
        jButtonVisualizacion.setVisible(false);
        jButtonComplejidad.setVisible(false);
    }
    
    public void mostrarBotones(){
        jButtonMST.setVisible(true);
        jButtonRecorrido.setVisible(true);
        jButtonSP.setVisible(true);
        jButtonVisualizacion.setVisible(true);
        jButtonComplejidad.setVisible(true);
    }
    
    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que quiere salir?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
        if (opcion == JOptionPane.YES_OPTION) {
            setVisible(false);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelPaneles = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneConsola = new javax.swing.JScrollPane();
        jPanelConsola = new javax.swing.JPanel();
        jButtonMST = new javax.swing.JButton();
        jButtonVisualizacion = new javax.swing.JButton();
        jButtonRecorrido = new javax.swing.JButton();
        jButtonSP = new javax.swing.JButton();
        jButtonComplejidad = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelLista = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPaneles.setOpaque(false);
        jPanelPaneles.setLayout(new java.awt.CardLayout());
        jPanelFondo.add(jPanelPaneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 300, 290));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(726, 549));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 810, 460));

        jScrollPaneConsola.setBorder(null);
        jScrollPaneConsola.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelConsola.setBackground(new java.awt.Color(239, 231, 218));

        javax.swing.GroupLayout jPanelConsolaLayout = new javax.swing.GroupLayout(jPanelConsola);
        jPanelConsola.setLayout(jPanelConsolaLayout);
        jPanelConsolaLayout.setHorizontalGroup(
            jPanelConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanelConsolaLayout.setVerticalGroup(
            jPanelConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jScrollPaneConsola.setViewportView(jPanelConsola);

        jPanelFondo.add(jScrollPaneConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 810, 160));

        jButtonMST.setBackground(new java.awt.Color(123, 63, 0));
        jButtonMST.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMST.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMST.setText("Árbol de Expansión Mínima ");
        jButtonMST.setBorder(null);
        jButtonMST.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMST.setFocusPainted(false);
        jButtonMST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMSTActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonMST, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 300, 50));

        jButtonVisualizacion.setBackground(new java.awt.Color(123, 63, 0));
        jButtonVisualizacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVisualizacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVisualizacion.setText("Visualización de grafo");
        jButtonVisualizacion.setBorder(null);
        jButtonVisualizacion.setBorderPainted(false);
        jButtonVisualizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizacion.setFocusPainted(false);
        jButtonVisualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizacionActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonVisualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 300, 50));

        jButtonRecorrido.setBackground(new java.awt.Color(123, 63, 0));
        jButtonRecorrido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRecorrido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecorrido.setText("Recorridos");
        jButtonRecorrido.setBorder(null);
        jButtonRecorrido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRecorrido.setFocusPainted(false);
        jButtonRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecorridoActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 300, 50));

        jButtonSP.setBackground(new java.awt.Color(123, 63, 0));
        jButtonSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSP.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSP.setText(" Rutas más cortas ");
        jButtonSP.setBorder(null);
        jButtonSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSP.setFocusPainted(false);
        jButtonSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSPActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 300, 50));

        jButtonComplejidad.setBackground(new java.awt.Color(123, 63, 0));
        jButtonComplejidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonComplejidad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComplejidad.setText("Reportes de complejidad ");
        jButtonComplejidad.setBorder(null);
        jButtonComplejidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonComplejidad.setFocusPainted(false);
        jPanelFondo.add(jButtonComplejidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 300, 50));

        jButtonSalir.setBackground(new java.awt.Color(123, 63, 0));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(null);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.setFocusPainted(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 710, 300, 50));

        jLabelTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 90)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 17, 9));
        jLabelTitulo.setText("GUANAJUATO");
        jPanelFondo.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 710, -1));

        jPanelLista.setBackground(new java.awt.Color(239, 231, 218));

        javax.swing.GroupLayout jPanelListaLayout = new javax.swing.GroupLayout(jPanelLista);
        jPanelLista.setLayout(jPanelListaLayout);
        jPanelListaLayout.setHorizontalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanelListaLayout.setVerticalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanelLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 300, 270));

        jPanel2.setBackground(new java.awt.Color(51, 17, 9));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1070, 10));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backgroundgif.gif"))); // NOI18N
        jLabelFondo.setText("jLabel2");
        jPanelFondo.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizacionActionPerformed

    }//GEN-LAST:event_jButtonVisualizacionActionPerformed

    private void jButtonMSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMSTActionPerformed
        
        ocultarBotones();
        CardLayout cl = (CardLayout) jPanelPaneles.getLayout();
        cl.show(jPanelPaneles, "MST");
    }//GEN-LAST:event_jButtonMSTActionPerformed

    private void jButtonSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSPActionPerformed
        
        ocultarBotones();
        CardLayout cl = (CardLayout) jPanelPaneles.getLayout();
        cl.show(jPanelPaneles, "RutaCorta");
    }//GEN-LAST:event_jButtonSPActionPerformed

    private void jButtonRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecorridoActionPerformed
        
        ocultarBotones();
        CardLayout cl = (CardLayout) jPanelPaneles.getLayout();
        cl.show(jPanelPaneles, "Recorridos");
    }//GEN-LAST:event_jButtonRecorridoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        cerrar();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaEstado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComplejidad;
    private javax.swing.JButton jButtonMST;
    private javax.swing.JButton jButtonRecorrido;
    private javax.swing.JButton jButtonSP;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVisualizacion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelConsola;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelLista;
    private javax.swing.JPanel jPanelPaneles;
    private javax.swing.JScrollPane jScrollPaneConsola;
    // End of variables declaration//GEN-END:variables
}
