/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.proyectofinal.presentacion;

/**
 *
 * @author Dana Chavez
 */
public class PanelRecorridos extends javax.swing.JPanel {

    private MapaEstado mapaEstado;
    
    public PanelRecorridos(MapaEstado mapaEstado) {
        initComponents();
        this.mapaEstado = mapaEstado;
        setOpaque(false);
        
    }
    
    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(300, 290));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 17, 9));
        jLabelTitulo.setText("Recorridos");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, -1));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gbotoncerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gbotonaceptar.png"))); // NOI18N
        jButtonAceptar.setBorder(null);
        jButtonAceptar.setContentAreaFilled(false);
        jButtonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        mapaEstado.mostrarPanel("vacio");
        mapaEstado.mostrarBotones();
    }//GEN-LAST:event_jButtonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
