
package itson.proyectofinal.presentacion;

public class PanelMST extends javax.swing.JPanel {
    private MapaEstado mapaEstado;

    public PanelMST(MapaEstado mapaEstado) {
        initComponents();
        setOpaque(false);
        this.mapaEstado = mapaEstado;
        
    }
    
    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCiudad = new javax.swing.JLabel();
        opcionesCiudades = new javax.swing.JComboBox<>();
        jLabelTitulo = new javax.swing.JLabel();
        opcionesMST = new javax.swing.JComboBox<>();
        jButtonCerrar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(300, 290));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCiudad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelCiudad.setForeground(new java.awt.Color(51, 17, 9));
        jLabelCiudad.setText("Ciudad inicial:");
        add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, -1));

        opcionesCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(opcionesCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 40));

        jLabelTitulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 17, 9));
        jLabelTitulo.setText("MST");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 70, -1));

        opcionesMST.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(opcionesMST, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 240, 40));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gbotoncerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gbotonaceptar.png"))); // NOI18N
        jButtonAceptar.setBorder(null);
        jButtonAceptar.setContentAreaFilled(false);
        jButtonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        mapaEstado.mostrarPanel("vacio");
        mapaEstado.mostrarBotones();
    }//GEN-LAST:event_jButtonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JComboBox<String> opcionesCiudades;
    private javax.swing.JComboBox<String> opcionesMST;
    // End of variables declaration//GEN-END:variables
}
